In [3]:
a = 5
a

5

In [ ]:
import numpy as np
data = {i : np.random.randn() for i in range(7)}
data



{0: -1.187064184900298,
 1: -0.945132272467715,
 2: -0.6408876548021791,
 3: 0.25636228857226123,
 4: -0.8585716542974271,
 5: 1.2397165945698225,
 6: -0.7488857748092287}

In [ ]:
b = [1,2,3]
b.sort  
import datetime
datetime.datetime.now() 
                                 

datetime.datetime(2024, 11, 19, 15, 31, 51, 362195)

In [7]:
b = [1,2,3]
b?
print?

Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method

In [11]:
def add_numbers(a , b):
    """Add two numbers together"""
    return a + b
add_numbers(2,3)


5

In [15]:
def append_element(some_list, element):
    some_list.append(element)
data = [1,2,3]
append_element(data,4)
data

[1, 2, 3, 4]

In [20]:
a = 5
type(a)
a = '5'
type(a)
isinstance(a,(int,str))

True

In [30]:
import some_module
from some_module import g ,PI
result = g(5, PI)

ImportError: cannot import name 'g' from 'some_module' (c:\Users\lenovo\Desktop\python_project\神经网络\JupyterNote\some_module.py)

In [5]:
a = [1 ,2, 3]
b = a
c = list(a)
a is b 
a is not c 
a_list = ['two', 2, [4,5]]
a_list[2] = (88,99)
a_list
a_list[1] = "one"
a_list

['two', 'one', (88, 99)]

In [11]:
ival = 176890
ival ** 5
fval =7.243
favl2 = 6.78e-5
3/2
3//2
c = """
This is a long string 
that will not fit on my screen.
"""
c.count('\n')
a = "hello world"
a[3] = 'f'
a




TypeError: 'str' object does not support item assignment

In [15]:
a = 5.5
b = str(a)
print(b)
c = 'python'
list(c)
c[:2]
c + b


5.5


'python5.5'

In [21]:
val = 'espanol'
val
val_utf8 = val.encode('utf-8')
val_utf8
type(val_utf8)
s = '3.14159'
fval = float(s)
type(fval)
int(fval)
bool(fval)

True

In [33]:
from datetime import datetime,date,time
dt = datetime(2015, 7, 18, 14, 33)
dt.day
dt.time
dt.minute
dt.date()
dt.time()
dt.strftime('%Y-%m-%d %H:%M')
date.today()
datetime.strptime('20241121' ,'%Y%m%d')
dt.replace(year=2090,minute=0)
dt2 = datetime(2030,11,14,12,23)
delta = dt2 - dt
delta
dt + delta

datetime.datetime(2030, 11, 14, 12, 23)

In [36]:
x = 5
if x < 0:
    print("negative")
elif x == 0:
    pass
elif 0<x<5:
    print('Positive but small')
else:
    print("Positive and large")


Positive and large


In [40]:
sequence = [1,2,0,4,6,2,1]
total_unti1_5 = 0
for value in sequence:
    if value == 5:
        break
    total_unti1_5 += value

for i in range(4):
    for j in range(4):
        if j > i:
            break
        print(i, j)

x = 256
total = 0
while x>0:
    if total > 500:
        break
    total += x
    x = x//2

0 0
1 0
1 1
2 0
2 1
2 2
3 0
3 1
3 2
3 3


In [45]:
range(10)
list(range(8))
list(range(99,89,-3))

[99, 96, 93, 90]

In [14]:
tup = ("foo","bar","baz")
b_list = list(tup)
b_list
b_list[2]= 'peekaboo'
b_list
b_list.append('dwarf')
b_list
b_list.insert(2,'red')
b_list
b_list.pop(2)
b_list.append('bar')
b_list
b_list.remove('bar')
b_list
'bar' in b_list
['foo','bar','baz'] + ['peekaboo','dwarf']
x = ['foo','bar','baz'] + ['peekaboo','dwarf']
x.append('None')
x

['foo', 'bar', 'baz', 'peekaboo', 'dwarf', 'None']

In [19]:
a = [1,5,6,90,66]
a.sort()
a
b = ['saw','small','fixes','seven','He']
b.sort(key=len)
b

['He', 'saw', 'small', 'fixes', 'seven']

In [27]:
import bisect
c = [1,2,2,2,3,6,7]
bisect.bisect(c,2)
bisect.bisect(c,9)
sequence = [7,0,4,3,5,4]
sequence[:3]
sequence[1:4]
sequence[1:4]=[1,2,3]
sequence
sequence[::-1]

[4, 5, 3, 2, 1, 7]

In [18]:
some_list = ['foo','var','bar','bza']
mapping = {}
for i, v in enumerate(some_list):
    mapping[i] = v
    print(i, v)
mapping
sorted([1,3,6,3,7,0])
sorted('hello  world')
sqe1 = ['foo','bar','vaz']
sqe2 = ['one','two','three']
zipped = zip(sqe1, sqe2)
list(zipped)
sqe3 = ['go','for']
list(zip(sqe1,sqe2,sqe3))
for i,(a,b) in enumerate(zip(sqe1,sqe2)):
    print('{0}: {1}, {2}'.format(i,a,b))

pitchers = [('Nolan','Ryan'),('Roger','Clemens'),('Schilling','Kyle')]
first_names, last_names = zip(*pitchers)
first_names
last_names
list(reversed(first_names))


0 foo
1 var
2 bar
3 bza
0: foo, one
1: bar, two
2: vaz, three


['Schilling', 'Roger', 'Nolan']

In [ ]:
empty_dict = {}
d1 = {'a': 'some vaule','b': '[1,2,3,4]'}
d1
d1[7] = 'an interger'
d1['a']
d1[5]= 'some value'
d1
del d1[5]
d1
ret = d1.pop('a')
ret
d1
list(d1.keys())
list(d1.values())
d1.update({'c':'anther word', 6: 'happy','b': 7})
d1
mapping = dict(zip(range(5),reversed(range(5))))
mapping

words = ['apple','bat','bar','atom','book']
by_letter = {}
for word in words:
    letter = word[0]
    if letter not in by_letter:
        by_letter[letter] = [word]
    else:
        by_letter[letter].append(word)
by_letter

for word in words:
    letter = word[0]
    by_letter.setdefault(letter,[]).append(word)
by_letter

hash("string")
hash((1,2,3,4,(2,3)))
hash(1,23,[2,3]) #由于列表可变，所以不能作为键


TypeError: hash() takes exactly one argument (3 given)

In [17]:
set([2,2,2,1,3,3])
{2,2,2,1,3,3}
a = {1,2,3,4,5}
b = {3,4,5,6,7,8}
a.union(b)
a | b
a.intersection(b)
a & b
c = a.copy()
c |= b
c
d = a.copy()
d &= b
d.clear()
d
b.add(119)
b
a.difference(b)
my_data = [1,2,3,4,5]
my_set = {tuple(my_data)}
my_set
a_set = {1,2,3,4,5}
{5,6,7}.issubset(a_set)
a_set.issuperset({1,2,3})
{1,2,3,} == {3,1,2}


True

In [33]:
strings = ['a','as','bat','car','dove','python']
[x.upper() for x in strings if len(x) > 2]
result = []
for x in strings:
    if len(x) > 2:
       
        result.append(x.upper())
        print(x.upper())
unique_length = {len(x) for x in strings}
unique_length
set(map(len,strings))
loc_mapping = {val : index for index, val in enumerate(strings)}
loc_mapping

all_data = [['john','emily','michael','mary','steven'],['maria','juan','javier','natalia','pilar']]
names_of_interest = []
for names in all_data:
    enough_es = [name for name in names if name.count('e') >= 2]
    names_of_interest.extend(enough_es)
names_of_interest
result = [name for names in all_data for name in names if name.count('e') >=2]
result

some_tuples = [(1,0),(2,0),(3,2)]
flattened = [x for tup in some_tuples for x in tup]
flattened
flattened = []
for tup in some_tuples:
    for x in tup:
        flattened.append(x)
flattened   

[[x for x in tup] for tup in some_tuples]


BAT
CAR
DOVE
PYTHON


[[1, 0], [2, 0], [3, 2]]

In [10]:
# Function,函数是python中重要的组成部分，函数是实现特定功能的代码块。
def func():
    a = []  #本地变量（函数内变量）命名空间
    for i in range(5):
        a.append(i)
        print(a)

a = []  #全局变量（函数外变量）命名空间
def func():
    for i in range(5):
        a.append(i)
print(a)

def f():
    a = 4
    b = 5
    c = 7
    return a,b,c
    return {'a': a, 'b': b, 'c': c}
a,c,b = f()


[]


In [16]:
states  = ['  Alababma','Georagia!','georgia','flOrida','south   carolina##','West virginia?']

import re
def clean_strings(strings): 
    result = []
    for value in strings:
        value = value.strip()
        value = re.sub('[!#?]','',value)
        value = value.title()
        result.append(value)
    return result
clean_strings(states)

def remove_punctuation(value):
    return re.sub('[!#?]','',value)

clean_ops = [str.strip,remove_punctuation,str.title]

def clean_strings(strings,ops):
    result = []
    for value in strings:
        for function in ops:
            value = function(value)
        result.append(value)
    return result
clean_strings(states,clean_ops)

for x in map(remove_punctuation,states):
    print(x)

  Alababma
Georagia
georgia
flOrida
south   carolina
West virginia


In [22]:
# Lambda function
def short_function(x):
    return x * 2
equiv_anon = lambda x : x * 2
def apply_to_list(some_list, function):
    return [function(x) for x in some_list]
ints = [4,0,1,5,6]
apply_to_list(ints,lambda x: x **2)

strings = ["foo","cards","var","aaaa","abcd"]
strings.sort(key= lambda x : len(set(list(x))))
strings

def add_numbers(x,y):
    return x +y
add_five = lambda x : add_numbers(5, y) #Curry function.

from functools import partial
add_five = partial(add_numbers, 5)


In [2]:
some_dict = {'a': 1, 'b': 2, 'c': 3}
for key in some_dict:
    print(key)
dict_iterator = iter(some_dict)
dict_iterator
list(dict_iterator)

gen = (x ** 2 for x in range(30))
gen
def _make_gen():
    for x in range(30):
        yield x ** 2
gen = _make_gen()

sum(x ** 2 for x in range(200))
dict((i, i ** 2) for i in range(5))

import itertools
first_letter = lambda x: x[0]
names = ['Alan', 'Adam', 'Wallace', 'Absalom','Will','Wes']
for letter,names in itertools.groupby(names,first_letter):
    print(letter,list(names))  # names is a generator

a
b
c
A ['Alan', 'Adam']
W ['Wallace']
A ['Absalom']
W ['Will', 'Wes']


In [10]:
float('1.2345')
def attempt_float(s):
    try:
        return float(s)
    except (ValueError, TypeError):
        return s
attempt_float('something')

path  = 'test.txt'
f = open(path,'w')
try:
    write_to_file(f)
except:
    print('Failed')
else:
    print('Succeeded')
finally:
    f.close()



Failed


In [16]:
path = '神经网络\JupyterNote\test.txt'
f = open(path)
for line in f:
    pass
lines = [x.rstrip() for x in open(path)]
lines

with open(path) as f:
    lines = [x.rstrip() for x in f] # 读取文件，并去掉换行符,with 语句适用于对资源进行访问的场合，确保不管使用过程中是否发生异常都会执行必要的“清理”操作，释放资源。

<>:1: SyntaxWarning: invalid escape sequence '\J'
<>:1: SyntaxWarning: invalid escape sequence '\J'
C:\Users\lenovo\AppData\Local\Temp\ipykernel_42004\4097005460.py:1: SyntaxWarning: invalid escape sequence '\J'
  path = '神经网络\JupyterNote\test.txt'


FileNotFoundError: [Errno 2] No such file or directory: '神经网络\\JupyterNote\test.txt'

In [20]:
# 第四章 NuPy 基础：数组与向量化计算

import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))
%time for _ in range(10): my_arr2 = my_arr * 2  # 数组计算
%time for _ in range(10): my_list2 = [x * 2 for x in my_list] # 列表生成式
# 通过上述两个例子，我们可以看出，数组计算要比列表生成式快很多。而且数组不需要使用for循环，直接通过数组运算即可完成。

#NumPy ndarry: 多维数组对象
import numpy as np
data = np.random.randn(2, 3) # 生成一个2行3列的随机数组
data
data * 10
data + data
data.shape
data.dtype

data2 = [6,7.5,8,0,1]
arr1 = np.array(data2)  # 将上述列表转换为数组，用np.array()函数,array is range 的数组版
arr1
data1 = [[1,2,3],[4,5,6]]
arr2 = np.array(data1)  # 将上述列表转换为多维数组，用np.array()函数自动识别
arr2
arr2.shape
arr2.ndim
arr1.dtype
arr2.dtype

np.zeros(10) # 生成10个0的数组
np.zeros((3 ,6)) # 生成3行6列的0数组
np.empty((2 ,3,2)) # 生成一个随机数组，数值未定义
np.arange(16) # 生成0-15的数组

CPU times: total: 31.2 ms
Wall time: 26 ms
CPU times: total: 172 ms
Wall time: 395 ms


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [12]:
# ndarray 数据类型 dytpe
import numpy as np
arr1 = np.array([1,2,3],dtype=np.float64)
arr2 = np.array([1,2,3],dtype=np.int32)
arr1.dtype
arr2.dtype
arr = np.array([1,2,3,4,5])
arr.dtype
float_arr = arr.astype(np.float64)
float_arr.dtype
arr = np.array([3.7,-1.2,-2.6,0.5,12.9,10.1])
arr
arr.astype(np.int32) # 截断小数点后面的数字
numeric_strings = np.array(['1.25','-9.6','42'],dtype=np.bytes_)
numeric_strings.astype(float)

int_array = np.arange(10)
calibers = np.array([.22,.270,.357,.380,.44,.50],dtype=np.float64)
int_array.astype(calibers.dtype)

empty_uint32 = np.empty(8, dtype='u4')
empty_uint32



array([   4128860,    6029375,    3801155,    5570652,    6619251,
          7536754, 3435593728,     393662], dtype=uint32)

In [ ]:
#Numpy 的数组算术，批量操作且不必for循环，此为向量化运算。逐元素操作。
arr = np.array([[1.,2.,3.],[4.,5.,6.]])
arr
arr * arr
arr - arr
1 / arr
arr ** 0.5

arr2 = np.array([[0.,4.,1.],[7.,2.,12.]])
arr2
arr2 > arr #产生布尔型数组，也是逐元素操作

# Numpy 数组的基础索引和切片操作
arr = np.arange(10)  #一维数组的操作与列表类似
arr
arr[5]
arr[5:8]  
arr[5:8] = 10 # 切片赋值,直接修改原数组而非复制或者创建新数组
arr
arr_slice = arr[5:8]
arr_slice
arr_slice[1] = 12345 # 修改切片值，原数组也会相应改变
arr
arr_slice[:] = 64
arr

arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]]) # 二维数组，返回的是数组对象，一维数组
arr2d[2]
arr2d[0][2]
arr2d[0,2]

arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])  #三维数组
arr3d
arr3d[0] # 返回的是二维数组对象
old_values = arr3d[0].copy() # 复制数组
arr3d[0] = 42
arr3d
arr3d[0] = old_values # 恢复数组
arr3d
arr3d[1,0]  #返回的一维数组对象

array([7, 8, 9])